"""F8 / F8b / F9 / F10 — detection, tiling, fusion, the operating threshold and the crop verifier.

**Importing this package must never import torch.** Everything re-exported here is numpy + stdlib; the two
classes that load a model (`rgb.RgbDetector`, `verifier.CropVerifier`) import Ultralytics / torch inside their
own constructors, so a machine whose GPU is busy with the Unreal editor can still import, test and run every
geometric and statistical part of the lane.

    from sightline.detect import TileGrid, detect_frame, merge_tile_detections   # F8 geometry
    from sightline.detect import choose_operating_threshold, freeze_operating_point  # 5.5 threshold rule
    from sightline.detect import fuse_detections, fuse_frame                     # F9 late fusion
    from sightline.detect import apply_verifier_output, suppress_false_positives # F10 + the 5.5a safety rule
    from sightline.detect import build_yolo_dataset, split_by_seed               # F8b data (seed-held-out)
"""

from sightline.detect.dataset import (
    CLASSES,
    MAX_TARGET_GROUND_M,
    CaptureFrame,
    CaptureLabel,
    CaptureRun,
    assert_boxes_are_plausible,
    assert_no_seed_leak,
    build_yolo_dataset,
    capture_box_to_xyxy,
    clip_box_to_tile,
    implausible_boxes,
    load_run,
    load_runs,
    plausible_labels,
    split_by_seed,
    summarise_boxes,
    tile_boxes,
    to_eval_dataset,
    yolo_line,
)
from sightline.detect.fusion import (
    MAX_RESIDUAL_PX,
    AltitudeHomographyTable,
    FusionResult,
    Registration,
    fuse_detections,
    fuse_frame,
    homography_from_intrinsics,
    register_thermal,
    thermal_weight,
    warp_boxes,
)
from sightline.detect.rgb import (
    RAW_CONF,
    DetectorConfig,
    boxes_to_detections,
    detect_bundle,
    detect_frame,
)
from sightline.detect.threshold import (
    PRIMARY_IOU,
    SECONDARY_IOU,
    TARGET_RECALL,
    FrameEval,
    GroundTruthBox,
    MatchTally,
    OperatingPoint,
    SweepPoint,
    choose_operating_threshold,
    fp_per_minute,
    freeze_operating_point,
    load_operating_point,
    match_frame,
    metric_rows,
    sliced_operating_points,
    sweep,
    tally,
)
from sightline.detect.tiler import (
    DEFAULT_OVERLAP,
    DEFAULT_TILE_PX,
    Tile,
    TileGrid,
    containment_xyxy,
    iou_xyxy,
    map_box_to_frame,
    merge_tile_detections,
    tile_batches,
    to_frame,
)
from sightline.detect.verifier import (
    BASE_URGENCY,
    URGENCY_RANK,
    VerifierDecision,
    VerifierOutput,
    apply_batch,
    apply_verifier_output,
    crop_for,
    suppress_false_positives,
    urgency_of,
)

__all__ = [
    "BASE_URGENCY",
    "CLASSES",
    "DEFAULT_OVERLAP",
    "DEFAULT_TILE_PX",
    "MAX_RESIDUAL_PX",
    "MAX_TARGET_GROUND_M",
    "PRIMARY_IOU",
    "RAW_CONF",
    "SECONDARY_IOU",
    "TARGET_RECALL",
    "URGENCY_RANK",
    "AltitudeHomographyTable",
    "CaptureFrame",
    "CaptureLabel",
    "CaptureRun",
    "DetectorConfig",
    "FrameEval",
    "FusionResult",
    "GroundTruthBox",
    "MatchTally",
    "OperatingPoint",
    "Registration",
    "SweepPoint",
    "Tile",
    "TileGrid",
    "VerifierDecision",
    "VerifierOutput",
    "apply_batch",
    "apply_verifier_output",
    "assert_boxes_are_plausible",
    "assert_no_seed_leak",
    "boxes_to_detections",
    "build_yolo_dataset",
    "capture_box_to_xyxy",
    "choose_operating_threshold",
    "clip_box_to_tile",
    "containment_xyxy",
    "crop_for",
    "detect_bundle",
    "detect_frame",
    "fp_per_minute",
    "freeze_operating_point",
    "fuse_detections",
    "fuse_frame",
    "homography_from_intrinsics",
    "implausible_boxes",
    "iou_xyxy",
    "load_operating_point",
    "load_run",
    "load_runs",
    "map_box_to_frame",
    "match_frame",
    "merge_tile_detections",
    "metric_rows",
    "plausible_labels",
    "register_thermal",
    "sliced_operating_points",
    "split_by_seed",
    "summarise_boxes",
    "suppress_false_positives",
    "sweep",
    "tally",
    "thermal_weight",
    "tile_batches",
    "tile_boxes",
    "to_eval_dataset",
    "to_frame",
    "urgency_of",
    "warp_boxes",
    "yolo_line",
]
